# Generated by Django 3.2.19 on 2024-08-28 10:27

import author.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=author.models.author_image_file_path),
        ),
    ]
